routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::get('', 'ProjectController@index')->name('home');
Route::resource('settings', 'SettingsController');


Route::get('environments/{environment}/setup', 'EnvironmentController@setup')->name('environments.setup');
Route::get('environments/{environment}/setupStatus', 'EnvironmentController@runSetupStatus')->name('environments.setupStatus');
Route::post('environments/{environment}/setup', 'EnvironmentController@runSetup')->name('environments.runSetup');
Route::post('environments/{environment}/control/{action}', 'EnvironmentController@controlEnvironment')->name('environments.control');
Route::get('environments/{environment}/control/{action}', 'EnvironmentController@controlEnvironmentModaL')->name('environments.controlModal');
Route::resource('environments', 'EnvironmentController');
Route::get('treeview', 'TreeviewController@dirTree')->name('treeview');


Route::get('projects/groups', 'ProjectController@groups')->name('projects.groups');
Route::get('projects/gitlabSearch', 'ProjectController@gitlabSearch')->name('projects.gitlabSearch');
Route::get('projects/types', 'ProjectController@types')->name('projects.types');
Route::post('projects/types', 'ProjectController@storeType')->name('projects.types.store');
Route::get('projects/types/create', 'ProjectController@createType')->name('projects.types.create');
Route::get('projects/types/{type}', 'ProjectController@editType')->name('projects.types.show');
Route::post('projects/types/{type}', 'ProjectController@updateType')->name('projects.types.update');
Route::get('projects/{project}/domain/{domain}/launch', 'ProjectController@domainLaunch')->name('projects.launch');
Route::get('projects/{project}/tabInfo/{tab}', 'ProjectController@tabInfo')->name('projects.tabInfo');
Route::get('projects/{project}/setup', 'ProjectController@setup')->name('projects.setup');
Route::get('projects/{project}/setupStatus', 'ProjectController@runSetupStatus')->name('projects.setupStatus');
Route::post('projects/{project}/setup', 'ProjectController@runSetup')->name('projects.runSetup');
Route::get('projects/{project}/configure', 'ProjectController@configure')->name('projects.configure');
Route::get('projects/config-gen', 'ProjectController@generateConfigFile')->name('projects.config_gen');
Route::post('projects/{project}/actions/{action}', 'ProjectController@actions')->name('projects.actions');
Route::get('projects/{project}/contents/{content}', 'ProjectController@contents')->name('projects.contents');
Route::get('projects/configfiles', 'ProjectController@configfiles')->name('projects.configfiles');
Route::get('projects/configfiles/create', 'ProjectController@createConfigFile')->name('projects.configfiles.create');
Route::get('projects/configfiles/{configfile}', 'ProjectController@editConfigFile')->name('projects.configfiles.edit');
Route::post('projects/configfiles/{configfile}', 'ProjectController@updateConfigFile')->name('projects.configfiles.update');
Route::resource('projects', 'ProjectController');
Route::get('seo', 'SeoController@index')->name('seo.index');
Route::get('seo/linkChecker', 'SeoController@linkChecker')->name('seo.linkChecker');
Route::get('seo/imgChecker', 'SeoController@imgChecker')->name('seo.imgChecker');
Route::prefix('tools')->group(function () {
	Route::get('', function () {
		return view('tools');
	})->name('tools');
});

app/Environment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Environment extends Model
{

    public $timestamps = false;
    public $validationRules = [
        'name' => 'required',
        'php_version' => 'required',
        'mysql_version' => 'required'
    ];

    /** @var App\Environments\Setup $setupClass * */
    private $setupClass = null;
    private $isRunning = null;
    private $apacheIsRunning = null;
    private $mysqlIsRunning = null;

    public function link($method = 'show', $params = [])
    {
        $params = array_merge(['id' => $this->id], $params);
        return route('environments.' . $method, $params);
    }

    public function isInstalled()
    {
        return file_exists($this->instanceFile());
    }

    public function isRunning()
    {
        if (!$this->isInstalled()) {
            return false;
        }
        if (is_null($this->isRunning)) {
            $this->isRunning = $this->apacheIsRunning();
        }
        return $this->isRunning;
    }

    public function apacheIsRunning()
    {
        if (!$this->isInstalled()) {
            return false;
        }
        if (is_null($this->apacheIsRunning)) {
            $this->apacheIsRunning = false;
            exec("sudo ssh root@{$this->ip_address} 'service apache2 status' 2>&1", $output);
            if (!empty($output[0])) {
                if(strpos($output[0], 'Connection refused') !== false){
                    $this->runCommand('service ssh start');
                }
                $this->apacheIsRunning = strpos($output[0], 'apache2 is running') !== false;
            }
        }
        return $this->apacheIsRunning;
    }

    public function mysqlIsRunning()
    {
        if (!$this->isInstalled()) {
            return false;
        }
        if (is_null($this->mysqlIsRunning)) {
            $this->mysqlIsRunning = false;
            exec("sudo ssh root@{$this->ip_address} 'service mysql status' 2>&1", $output);
            if(strpos($output[0], 'Connection refused') !== false){
                $this->runCommand('service ssh start');
            }
            if (!empty($output[0]) && strpos($output[0], 'Permission denied') === false) {
                $this->mysqlIsRunning = !(strpos($output[0], 'MySQL is stopped') !== false);
            }
        }
        return $this->mysqlIsRunning;
    }

    public function start()
    {
        $this->runCommand('service apache2 start');
        //$this->runCommand('service mysql start');
        $this->runCommand('service php5.6-fpm start');
		$this->runCommand('service mailhog start');
    }

    public function stop()
    {
        $this->runCommand('service apache2 stop');
        //$this->runCommand('service mysql stop');
        $this->runCommand('service php5.6-fpm stop');
		$this->runCommand('service mailhog stop');
    }

    public function runCommand($cmd = false, $wait = true)
    {
        $ending = $wait ? '2>&1' : '> /dev/null 2>/dev/null &';
        $windowsInstance = str_replace('\\', '\\\\', \App\DirTree::directoryToWindows($this->instanceFile()));
        if ($cmd) {
            //echo "/mnt/c/Windows/System32/cmd.exe /c start {$windowsInstance} run \"{$cmd}\" 2>&1";
            //die();
            $output = shell_exec("/mnt/c/Windows/System32/cmd.exe /c start {$windowsInstance} run \"{$cmd}\" $ending");
        } else {
            $output = shell_exec("/mnt/c/Windows/System32/cmd.exe /c start {$windowsInstance} $ending");
            //$output = shell_exec("/mnt/c/Windows/System32/cmd.exe /c start {$windowsInstance} > /dev/null 2>/dev/null &");
        }
        return $output;
    }

    public function runCommandBackground($cmd = false)
    {
        $windowsInstance = str_replace('\\', '\\\\', \App\DirTree::directoryToWindows($this->instanceFile()));
        if ($cmd) {
            echo "/mnt/c/Windows/System32/cmd.exe {$windowsInstance} run \"{$cmd}\" 2>&1";
            $output = shell_exec("/mnt/c/Windows/System32/cmd.exe {$windowsInstance} run \"{$cmd}\" 2>&1");
        } else {
            $output = shell_exec("/mnt/c/Windows/System32/cmd.exe {$windowsInstance} > /dev/null 2>/dev/null &");
        }
        return $output;
    }

    public function isSetup()
    {
        if (is_dir($this->folder())) {
            return true;
        }
        return false;
    }

    public function cleanName()
    {
        return str_replace(' ', '_', $this->name);
    }

    public function folder()
    {
        return Settings::environment('root_dir') . '/' . $this->cleanName();
    }

    public function instanceFile()
    {
        return $this->folder() . '/' . $this->cleanName() . '.exe';
    }

    /**
     *
     * @return App\Environment\Setup
     */
    public function setupClass()
    {
        if (is_null($this->setupClass)) {
            $this->setupClass = new \App\Environment\Setup($this);
        }
        return $this->setupClass;
    }

    public function delete()
    {
        $this->uninstall();
        return parent::delete();
    }

    public function uninstall(){
        $windowsInstance = str_replace('\\', '\\\\', \App\DirTree::directoryToWindows($this->instanceFile()));
        shell_exec("/mnt/c/Windows/System32/cmd.exe /c start {$windowsInstance} clean 2>&1");
        shell_exec("sudo rm -rf {$this->folder()}");
    }

    public function generateIcon(){
        $im = imagecreatetruecolor(256, 256);
        $bg = imagecolorallocate($im, 43,158,235);
        $textshadow = imagecolorallocate($im, 128, 128, 128);
        $textcolor = imagecolorallocate($im, 240,248,253);
        imagefilledrectangle($im, 0, 0, 256, 256, $bg);
        $text = $this->abbrev;
        $font = '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf';
        switch(strlen($text)){
            case 3:
                $shadow_x = -10;
                $text_x = -8;
                break;
            case 2:
                $shadow_x = 39;
                $text_x = 41;
                break;
            case 1:
                $shadow_x = 84;
                $text_x = 86;
                break;
        }
        imagettftext($im, 100, 0, $shadow_x, 178, $textshadow, $font, $text);
        imagettftext($im, 100, 0, $text_x, 176, $textcolor, $font, $text);
        imagepng($im, $this->folder().'/icon_256.png');

        //resize images using imagemagick
        shell_exec("convert {$this->folder()}/icon_256.png -resize 16x16 {$this->folder()}/icon_16.png 2>&1");
        shell_exec("convert {$this->folder()}/icon_256.png -resize 32x32 {$this->folder()}/icon_32.png 2>&1");
        shell_exec("convert {$this->folder()}/icon_256.png -resize 64x64 {$this->folder()}/icon_64.png 2>&1");
        shell_exec("convert {$this->folder()}/icon_256.png -resize 128x128 {$this->folder()}/icon_128.png 2>&1");
        shell_exec("convert {$this->folder()}/icon_16.png {$this->folder()}/icon_32.png {$this->folder()}/icon_64.png {$this->folder()}/icon_128.png {$this->folder()}/icon_256.png -colors 256 {$this->folder()}/icon.ico 2>&1");
    }

}

app/Http/Controllers/EnvironmentController.php
<?php

namespace App\Http\Controllers;

use App\ResourceHacker;
use Illuminate\Http\Request;
use App\Environment;
use Validator;
use Illuminate\Support\Facades\Input;
use App\Settings;

class EnvironmentController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!Settings::isSectionConfigured('environment')) {
            return redirect()->route('settings.index', ['tab' => 'environment']);
        }

        $environments = Environment::orderBy('name', 'asc')->get();

        return view('environments.index')
            ->with('environments', $environments);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->ae(new Environment());
    }

    public function ae(Environment $environment)
    {
        $aeActions = $this->handleAeActions();
        if ($aeActions !== false) {
            return response()->json($aeActions);
        }

        return view('environments.ae')->with('environment', $environment);
    }

    public function handleAeActions()
    {
        if (!empty($_GET['projectAeAction'])) {
            switch ($_GET['projectAeAction']) {
                case 'php_extensions':
                    return false;
                    break;
            }
        }
        return false;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->save($request, new Environment());
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Environment $environment)
    {
        if (!$environment->isSetup()) {
            return redirect()->route('environments.setup', ['environment' => $environment]);
        }
        return view('environments.view')->with('environment', $environment);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Environment $environment)
    {
        return $this->ae($environment);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $environment = Environment::find($id);
        return $this->save($request, $environment);
    }

    public function save(Request $request, Environment $environment)
    {
        $return = ['status' => 'error', 'errFlds' => []];
        $validator = Validator::make(Input::all(), $environment->validationRules);
        if ($validator->fails()) {
            $return['errFlds'] = $validator->errors();
        } else {
            // store
            $environment->name = Input::get('name');
            $environment->abbrev = Input::get('abbrev');
            $environment->apache_mods = implode(',', Input::get('apache_mods', []));
            $environment->php_extensions = implode(',', Input::get('php_extensions', []));
            $environment->php_version = Input::get('php_version');
            $environment->mysql_version = Input::get('mysql_version');
            $environment->save();
            if (!$environment->ip_address) {
                $environment->ip_address = '172.16.0.' . $environment->id;
                $environment->save();
            }
            $return['status'] = 'success';
            $return['msg'] = 'Environment Saved Successfully';
        }
        return response()->json($return);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function setup(Environment $environment)
    {
        return view('environments.setup')->with('environment', $environment);
    }

    public function runSetup(Environment $environment)
    {
        $environment->setupClass()->run();
    }

    public function runSetupStatus(Environment $environment)
    {
        return $environment->setupClass()->statusResponse();
    }

    public function controlEnvironment(Environment $environment, $action)
    {
        $response = ['status' => 'error'];
        switch ($action) {
            case 'start':
                $environment->start();
                $response['status'] = 'success';
                break;
            case 'stop':
                $environment->stop();
                $response['status'] = 'success';
                break;
            case 'restart':
                $environment->stop();
                $environment->start();
                $response['status'] = 'success';
                break;
            case 'remove':
                $environment->delete();
                $response['status'] = 'success';
                break;
            case 'uninstall':
                $environment->uninstall();
                $response['status'] = 'success';
                break;
            case 'terminal':
                $environment->runCommand(false, false);
                $response['status'] = 'success';
                break;
            case 'updateIcon':
                $environment->abbrev = Input::get('abbrev');
                $environment->save();
                $environment->generateIcon();
                ResourceHacker::addIcon($environment, $environment->folder().'/icon.ico');
                $response['status'] = 'success';
                $response['msg'] = 'Icon has been updated successfully';
                break;
        }
        return response()->json($response);
    }

    public function controlEnvironmentModal(Environment $environment, $action)
    {
        $response = 'Error';
        switch ($action) {
            case 'updateIcon':
                $response =  view('environments.modals.updateIcon')->with('environment', $environment);
                break;

        }
        return $response;
    }

}

resources/views/environments/ae.blade.php
{!! Form::model($environment, ['route' => ['environments.update', $environment->id], 'class'=>'needs-validation']) !!}
<h3>Environment Info</h3>
<div class="form-group">
    {!! Form::label('name', 'Name', ['class' => 'control-label', 'required'=>true]) !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'required'=>true]) !!}
    <div class="invalid-feedback">
        Please enter a Name.
    </div>
</div>
<div class="form-group">
    {!! Form::label('abbrev', 'Icon Text (max 3 chars)', ['class' => 'control-label', 'required'=>true]) !!}
    {!! Form::text('abbrev', null, ['class' => 'form-control', 'required'=>true]) !!}
    <div class="invalid-feedback">
        Please enter the text for the icon.
    </div>
</div>
<div class="form-group">
    {!! Form::label('apache_mods', 'Apache Modules', ['class' => 'control-label', 'required'=>false]) !!} <br/>
    {!! Form::checkboxes('apache_mods[]', \App\Environment\Setup\Apache::availableMods(),\App\Environment\Setup\Apache::$defaultMods, ['class' => 'form-check-input', 'required'=>true]) !!}
    <div class="invalid-feedback">
        Please select the Php version for the environment.
    </div>
</div>
<div class="form-group">
    {!! Form::label('php_version', 'PHP Version', ['class' => 'control-label', 'required'=>true]) !!}
    {!! Form::select('php_version', array_combine(\App\Environment\Setup\Php::versions(),\App\Environment\Setup\Php::versions()),'5.6', ['class' => 'form-control', 'required'=>true]) !!}
    <div class="invalid-feedback">
        Please select the Php version for the environment.
    </div>
</div>
<div class="form-group">
    {!! Form::label('php_extensions', 'PHP Extensions', ['class' => 'control-label', 'required'=>false]) !!} <br/>
    {!! Form::checkboxes('php_extensions[]', \App\Environment\Setup\Php::extensions('5.6'),\App\Environment\Setup\Php::defaultExtensions('5.6'), ['class' => 'form-check-input', 'required'=>true]) !!}
    <div class="invalid-feedback">
        Please select the Php version for the environment.
    </div>
</div>
<div class="form-group">
    {!! Form::label('mysql_version', 'Mysql Version', ['class' => 'control-label', 'required'=>true]) !!}
    {!! Form::select('mysql_version', array_combine(\App\Environment\Setup\Mysql::versions(),\App\Environment\Setup\Mysql::versions()),'5.6', ['class' => 'form-control', 'required'=>true]) !!}
    <div class="invalid-feedback">
        Please select the Php version for the environment.
    </div>
</div>
<div class="form-group">
    {!! Form::submit('Save Environment',['class' => 'btn btn-primary ajaxForm']) !!}
</div>
{!! Form::close() !!}
<script>
    $(function(){
       $('#php_version').change(function(e){

       });
    });
</script>

resources/views/environments/index.blade.php
@extends('layouts.app')

@section('content')
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <h1 class="my-4">Environments
            <small><a class="btn btn-primary ajaxModal" href="{{ route("environments.create") }}" data-size="large">Add Environment</a>
            </small>
        </h1>
        @if (count($environments) > 0)
            <table class="table table-striped table-bordered table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Apache</th>
                    <th>Ip Address</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($environments as $environment)
                    <tr>
                        <td><a href="{{ $environment->link() }}">{{ $environment->name }}</a></td>
                        <td><span class="stopped">{{ $environment->apacheIsRunning() ? 'Running' : 'Stopped' }}</span>
                        </td>
                        <td>{{ $environment->ip_address }}</td>
                        <td>
                            <a href="{{ $environment->link() }}" title="View" class="btn btn-sm btn-secondary"><i
                                        class="fa fa-eye"></i> View</a>
                            @if(!$environment->isInstalled())
                                <a href="{{ $environment->link('setup') }}"
                                   class="btn btn-sm btn-secondary" title="Stop"><i
                                            class="fa fa-cogs"></i> Setup</a>
                            @elseif ($environment->isRunning())
                                <a href="{{ $environment->link('control', ['action'=>'stop']) }}"
                                   class="btn btn-sm btn-secondary controlEnvironment" title="Stop"><i
                                            class="fa fa-power-off"></i> Stop</a>
                            @else
                                <a href="{{ $environment->link('control', ['action'=>'start']) }}"
                                   class="btn btn-sm btn-secondary controlEnvironment" title="Start"><i
                                            class="fa fa-play"></i> Start</a>
                            @endif
                            <a href="{{ $environment->link('control', ['action'=>'terminal']) }}"
                               class="btn btn-sm btn-secondary controlEnvironment" title="Show Terminal"><i
                                        class="fa fa-terminal"></i> Terminal</a>
                            @if($environment->isInstalled())
                                <a href="{{ $environment->link('control', ['action'=>'uninstall']) }}" title="View" class="btn btn-sm btn-secondary btn-danger controlEnvironment"
                                   data-confirm="Are you sure you want to uninstall {{ $environment->name }} Environment?">
                                    <i class="fa fa-remove"></i> Uninstall</a>
                            @endif
                            <a href="{{ $environment->link('control', ['action'=>'remove']) }}" title="View" class="btn btn-sm btn-secondary btn-danger controlEnvironment"
                               data-confirm="Are you sure you want to remove {{ $environment->name }} Environment?">
                                <i class="fa fa-trash"></i> Remove</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <!-- /.row -->
        @else
            <p class="alert alert-info">There are no Environments set up yet.</p>
        @endif
    </div>
    <!-- /.container -->
@endsection

resources/views/environments/setup.blade.php
@extends('layouts.app')

@section('content')
<!-- Page Content -->
<div class="container">

	<!-- Page Heading -->
	<h1 class="my-4">Environments - 
		<small>Setup {{$environment->name}}</small>
	</h1>
	<div class="well col-12">
		<a href="{{ $environment->link('setup') }}" data-statuslink='{{ $environment->link('setupStatus') }}' class="btn btn-primary environmentSetup col-12">Setup Environment</a>
	</div>
	<ul class="list-group list-group-root well">
		@foreach($environment->setupClass()->getSteps() as $step)
		<li class="list-group-item">{{ucwords(str_replace('_', ' ', $step))}}</li>
		@endforeach
	</ul>
</div>
<!-- /.container -->
@endsection

resources/views/environments/view.blade.php
@extends('layouts.app')

@section('content')
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <h1 class="my-4">
            <a href="{{route('environments.index')}}" class="btn btn-sm btn-secondary"><i class="fa fa-arrow-left"></i></a> Environments -
            <small>{{$environment->name}}</small>
        </h1>
        <div class="card">
            <h3 class="card-header">Actions</h3>
            <div class="card-body">
                <a href="{{$environment->link('control', ['action'=>'start'])}}" class="btn btn-secondary controlEnvironment{{$environment->isRunning() ? " disabled" : '' }}" title='Start'><i class="fa fa-play"></i>Start</a>
                <a href="{{$environment->link('control', ['action'=>'stop'])}}" class="btn btn-secondary controlEnvironment{{!$environment->isRunning() ? " disabled" : '' }}" title='Stop'><i
                            class="fa fa-power-off"></i>Stop</a>
                <a href="{{$environment->link('control', ['action'=>'restart'])}}" class="btn btn-secondary controlEnvironment{{!$environment->isRunning() ? " disabled" : '' }}" title="Restart"><i
                            class="fa fa-sync"></i>Restart</a>
                <a href="{{$environment->link('controlModal', ['action'=>'updateIcon'])}}" class="btn btn-secondary ajaxModal" title="Update Icon"><i
                            class="fa fa-pencil-square"></i>Update Icon</a>
                <a href="{{ $environment->link('control', ['action'=>'terminal']) }}" class="btn btn-sm btn-secondary controlEnvironment" title="Show Terminal"><i
                            class="fa fa-terminal"></i> Terminal</a>
                @if($environment->isInstalled())
                    <a href="{{ $environment->link('control', ['action'=>'uninstall']) }}" title="View" class="btn btn-sm btn-secondary btn-danger controlEnvironment"
                       data-confirm="Are you sure you want to uninstall {{ $environment->name }} Environment?">
                        <i class="fa fa-remove"></i> Uninstall</a>
                @endif
                <a href="{{ $environment->link('control', ['action'=>'remove']) }}" title="View" class="btn btn-sm btn-secondary btn-danger controlEnvironment"
                   data-confirm="Are you sure you want to remove {{ $environment->name }} Environment?">
                    <i class="fa fa-trash"></i> Remove</a>
            </div>
        </div>
        <div class="card">
            <h3 class="card-header">Environment Status</h3>
            <div class="card-body">
                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Name</td>
                        <td>{{$environment->name}}</td>
                    </tr>
                    <tr>
                        <td>IP address</td>
                        <td>{{$environment->ip_address}}</td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td>
                            @if($environment->isRunning())
                                <i class="fa fa-check-circle" style="color:green"></i> Environment is Running
                            @else
                                <i class="fa fa-times-circle" style="color:red"></i> Environment is not Running
                            @endif
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Planned Features
                        </button>
                    </h5>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-success">Ability to determine if its running or not and to start/stop it from running (stopping may be hard)</li>
                            <li class="list-group-item list-group-item-warning">Get info on server, apache/mysql/php version</li>
                            <li class="list-group-item list-group-item-warning">Ability to run updates (apt-get update)</li>
                            <li class="list-group-item list-group-item-success">As of right now I'm assigning ip address for the env by building Hyper-V virtual network interface
                                https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network, need to make that more intuitive (need to specifically build that automatically then
                                set the /etc/apache2/ports.conf file to listen on envip:port instead of just listening on all ips for the ports). This is a limitation of WSL and using a Hyper-V nat network is the
                                only way I have found around it. Making each environment apache only listen for the specific ip allows multiple of them to listen on the same port on the computer. Also bind-address
                                for [mysqld] in the /etc/mysql/my.cnf needs to be set to the env ip.
                            </li>
                            <li class="list-group-item list-group-item-warning">Add Ability to run additional scripts on the environment (apt commands, anything), can even add some helper tools at some point for this like installing php
                                libraries (can use apt-cache pkgnames | grep php{version}-* on env to get list of packages)
                            </li>
                            <li class="list-group-item list-group-item-success">I want to be able to on add assign 2-3 letters that are then converted to an icon. I then want to figure out how to make the .exe for the environment use the
                                icon generated (IE Basesite envrionment could have an icon on your computer with letters BS to make it easy to distinguish which env is which) -- Did some looking into this, in order
                                to assign an icon to the exe the only way i have found is to use Resource Hacker found here http://www.angusj.com/resourcehacker/ . This does have a command line interface so I think
                                that this should still be possible will just have to require that to be installed on the computer in order for it to work.
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->
@endsection